# serverless.yml
service: serverless_test
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-north-1
  memorySize: 512
functions:
  getAllData:
    handler: backend-srvc.handler
    events:
      - http:
          path: getAllData
          method: get
plugins:
  - serverless-offline